name: Build/Test/Deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+.[0-9]+
  pull_request:
      
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['centos:centos7', 'rockylinux:8', 'quay.io/centos/centos:stream8']
        components: ['udt,myproxy,ssh', 'gram5']
        # Ignore UDT for the CentOS Stream 9 case because libnice is not available there yet
        include:
          - image: 'quay.io/centos/centos:stream9'
            components: 'myproxy,ssh'
          - image: 'quay.io/centos/centos:stream9'
            components: 'gram5'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
    
      - name: build/test on ${{ matrix.image }} with ${{ matrix.components }}
        env:
          IMAGE: ${{ matrix.image }} 
          TASK: tests
          COMPONENTS: ${{ matrix.components }} 
        run: travis-ci/setup_tasks.sh
        
      - name: build source tarballs and srpms
        # Only run this step for the centos:centos7 case and for only one component selection
        if: |
          contains(matrix.image , 'centos:centos7') &&
          contains(matrix.components , 'udt,myproxy,ssh')
        env:
          IMAGE: centos:centos7
          TASK: srpms
        run: travis-ci/setup_tasks.sh
      
      # SSH key recipe from https://www.webfactory.de/blog/use-ssh-key-for-private-repositories-in-github-actions
      - name: Establish ssh and upload source tarballs
        # Only run this step for the centos:centos7 case
        if: |
          contains(matrix.image , 'centos:centos7') &&
          contains(github.ref , 'refs/tags/')
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
          ssh-add - <<< "${{ secrets.ID_GCTUPLOADER }}"
          travis-ci/upload_source_tarballs.sh ${{ github.repository_owner }}
